version: '3.7'
services:

  # I N F R A S T R U C T U R E
  polynote:
    container_name: polynote
    image: polynote/polynote:0.3.7-2.12
    command: --config /opt/config/config.yml
    ports:
      - 8192:8192
    volumes:
      - "./config.yml:/opt/config/config.yml"
      - "../notebooks:/opt/notebooks/"
    restart: always